version: "3.8"

volumes:
  consul-volume:

services:
  consul-mesh:
    container_name: CONSUL_REGISTRY
    image: bitnami/consul:1.20.2
    profiles: ["side"]
    ports:
      - 8500:8500
    volumes:
      - consul-volume:/bitnami