version: "3.8"

volumes:
  go-cache:
  postgres-volume:

services:
  postgres:
    container_name: POSTGRESQL
    image: timescale/timescaledb:2.5.2-pg14-oss
    profiles: ["side"]
    ports:
      - 8010:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: 4gDokQ*hMT_4d2rZqy!8mUExF24w!FkU
      POSTGRES_DB: dev-db
