version: "3.8"

volumes:
  consul-volume:

services:
  consul-mesh:
    container_name: CONSUL_REGISTRY
    image: bitnami/consul:1.20.2
    profiles: ["side"]
    ports:
      - "127.0.0.1:8500:8500"
    volumes:
      - consul-volume:/bitnami
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_HTTP_ADDR=0.0.0.0

  traefik:
    container_name: TRAEFIK_GATEWAY
    image: traefik:latest
    profiles: ["side"]
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      consul-mesh:
        condition: service_started